{{- if and .Values.driftCallback.enabled .Values.driftCallback.ca.cert }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kausality.fullname" . }}-callback-ca
  labels:
    {{- include "kausality.labels" . | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ .Values.driftCallback.ca.cert | b64enc }}
{{- end }}
