{{- if .Values.controller.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kausality.controllerServiceAccountName" . }}
  labels:
    {{- include "kausality.controllerLabels" . | nindent 4 }}
{{- end }}
