{{- if and .Values.resourceRules.include (not .Values.certificates.selfSigned.enabled) }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "kausality.fullname" . }}
  labels:
    {{- include "kausality.labels" . | nindent 4 }}
  {{- if .Values.certificates.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "kausality.certificateSecretName" . }}
  {{- end }}
webhooks:
  - name: mutating.webhook.kausality.io
    admissionReviewVersions: ["v1"]
    sideEffects: NoneOnDryRun
    reinvocationPolicy: IfNeeded
    timeoutSeconds: 10
    failurePolicy: Fail
    matchPolicy: Equivalent
    clientConfig:
      service:
        name: {{ include "kausality.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate
        port: {{ .Values.service.port }}
    rules:
      {{- range .Values.resourceRules.include }}
      - apiGroups:
          {{- toYaml .apiGroups | nindent 10 }}
        apiVersions: ["*"]
        resources:
          {{- toYaml .resources | nindent 10 }}
        operations:
          - CREATE
          - UPDATE
          - DELETE
        scope: "*"
      {{- end }}
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            {{- toYaml .Values.excludeNamespaces | nindent 12 }}
{{- end }}
